import { randomUUID } from "node:crypto";
import { runArena } from "./arena/orchestrator.js";
import { suggestPerspectives } from "./arena/perspectives.js";
import { formatDebateSummary } from "./arena/debate-summary.js";
import { runOrchestratorFromMarkdown } from "./todo/orchestrator.js";
import { createDefaultConstitution } from "./constitution/defaults.js";
import { extractDecisions } from "./arena/orchestrator.js";
import { savePipelineIndex, saveArenaTrace, saveTodoTrace, appendToIndex } from "./trace/store.js";
import type { TraceOptions } from "./trace/types.js";
import type { ArenaConfig, LLMProvider, ArenaResult, PerspectiveSuggestion } from "./arena/types.js";
import type { NodeExecutor, ExecutionReport } from "./todo/types.js";
import type { Constitution } from "./constitution/types.js";

export type PipelineMode = "full" | "arena-only" | "execute-only" | "perspectives";

export interface PipelineOptions {
  plan: string;
  llm: LLMProvider;
  executor: NodeExecutor;
  constitution?: Constitution;
  arena?: Partial<ArenaConfig>;
  outputDir?: string;
  pipelineId?: string;
  mode?: PipelineMode;
  todoMarkdown?: string;
  /** Pre-confirmed perspectives (decision title → persona list). If not set, runs suggestPerspectives in full/arena-only mode. */
  perspectives?: Map<string, string[]>;
  trace?: TraceOptions;
}

export interface PipelineResult {
  pipelineId: string;
  revisedPlan: string;
  todoMarkdown: string;
  report: ExecutionReport | null;
  arenaResult: ArenaResult;
  /** Generated by suggestPerspectives in "perspectives" mode. */
  perspectivesSuggestions?: Array<{ decision: string; perspectives: PerspectiveSuggestion[] }>;
  /** Generated by formatDebateSummary after Arena. */
  debateSummary?: string;
}

export async function runPipeline(options: PipelineOptions): Promise<PipelineResult> {
  const now = new Date().toISOString().replace(/[:.]/g, "").slice(0, 17);
  const hex = randomUUID().slice(0, 6);
  const pipelineId = options.pipelineId ?? `${now}-${hex}`;
  const mode = options.mode ?? "full";
  const constitution = options.constitution ?? createDefaultConstitution();

  let revisedPlan = options.plan;
  let todoMarkdown = "";
  let debateSummary = "";
  let perspectivesSuggestions: PipelineResult["perspectivesSuggestions"];

  // ---- Perspectives phase ----
  if (mode === "full" || mode === "arena-only" || mode === "perspectives") {
    if (options.perspectives) {
      // Use pre-confirmed perspectives (no LLM call needed)
      perspectivesSuggestions = [...options.perspectives.entries()].map(([decision, personas]) => ({
        decision,
        perspectives: personas.map((p) => ({ persona: p, reason: "pre-confirmed" })),
      }));
    } else {
      // Auto-suggest via LLM
      const decisions = extractDecisions(options.plan);
      perspectivesSuggestions = await suggestPerspectives(options.llm, decisions, constitution);
    }
  }

  if (mode === "perspectives") {
    return {
      pipelineId,
      revisedPlan: options.plan,
      todoMarkdown: "",
      report: null,
      arenaResult: { state: null!, problemsBattled: 0, recursiveBattles: 0, durationMs: 0 },
      perspectivesSuggestions,
    };
  }

  // ---- Arena phase ----
  const arenaConfig: ArenaConfig = {
    maxDepth: options.arena?.maxDepth ?? 2,
    maxCritiqueCycles: options.arena?.maxCritiqueCycles ?? 1,
    outputDir: options.outputDir,
  };

  let arenaResult: ArenaResult;

  if (mode === "execute-only") {
    if (!options.todoMarkdown) throw new Error("todoMarkdown is required in execute-only mode");
    todoMarkdown = options.todoMarkdown;
    arenaResult = { state: null!, problemsBattled: 0, recursiveBattles: 0, durationMs: 0 };
  } else {
    arenaResult = await runArena(arenaConfig, options.llm, options.plan, constitution);
    if (!arenaResult.state.synthesis) {
      throw new Error("Arena completed without synthesis result");
    }
    revisedPlan = arenaResult.state.synthesis.revisedPlan;
    todoMarkdown = arenaResult.state.synthesis.todoMarkdown;
    debateSummary = formatDebateSummary(arenaResult.state);
  }

  // ---- Execution phase ----
  let report: ExecutionReport | null = null;
  if (mode === "full" || mode === "execute-only") {
    report = await runOrchestratorFromMarkdown(todoMarkdown, options.executor, { maxRetries: 0 });
  }

  const result: PipelineResult = {
    pipelineId,
    revisedPlan,
    todoMarkdown,
    report,
    arenaResult,
    perspectivesSuggestions,
    debateSummary,
  };

  if (options.trace?.enabled) {
    const traceDir = options.trace.outputDir || "output/traces";
    savePipelineIndex(pipelineId, options.trace.planPath ?? null, traceDir);
    saveArenaTrace(pipelineId, options.trace.planPath ?? null, result, traceDir);
    if (report) saveTodoTrace(pipelineId, result, traceDir);
    appendToIndex(pipelineId, traceDir, {
      time: new Date().toISOString(),
      planPath: options.trace.planPath ?? null,
      decisionsCount: arenaResult.problemsBattled,
      todoCompleted: report?.completed ?? 0,
      todoTotal: report?.totalNodes ?? 0,
    });
  }

  return result;
}
